export default [
    require("./assets/WarCardGameAssets/back.png"),
    require("./assets/WarCardGameAssets/card2.png"),
    require("./assets/WarCardGameAssets/card3.png"),
    require("./assets/WarCardGameAssets/card4.png"),
    require("./assets/WarCardGameAssets/card5.png"),
    require("./assets/WarCardGameAssets/card6.png"),
    require("./assets/WarCardGameAssets/card7.png"),
    require("./assets/WarCardGameAssets/card8.png"),
    require("./assets/WarCardGameAssets/card9.png"),
    require("./assets/WarCardGameAssets/card10.png"),
    require("./assets/WarCardGameAssets/card11.png"),
    require("./assets/WarCardGameAssets/card12.png"),
    require("./assets/WarCardGameAssets/card13.png"),
    require("./assets/WarCardGameAssets/card14.png"),
]